export const GET_PROJECTS= 'GET_PROJECTS';
export const GET_DETAIL = "GET_DETAIL";
export const REMOVE_DETAIL = "REMOVE_DETAIL";
export const GET_PROJECT_BY_NAME="GET_PROJECT_BY_NAME";
export const GET_IMAGES= "GET_IMAGES";
export const SHOW_HOVER= "SHOW_HOVER";
